/*
 * PROJETO.c
 *
 * Created: 05/02/2026 15:37:07
 * Author : luizh
 */

 #define F_CPU 16000000UL
 #include <avr/io.h>
 #include <util/delay.h>
 #include <avr/interrupt.h>
 
volatile uint16_t leitura_adc = 1023; //VARIÁVEL QUE ARMAZENA A PALAVRA DECIMAL FEITA PELO ADC (COMEÇA EM 1023 E VAI DIMINUINDO)

ISR(ADC_vect){ //INTERRUPÇÃO QUE OCORRE A CADA 1ms (64 * (249 + 1) / 16 MHz) PARA GUARDAR O VALOR LIDO PELO ADC NA VARIÁVEL
	
	leitura_adc = ADC; //VARIÁVEL GUARDANDO VALOR DIRETAMENTE DO REGISTRADOR DO ADC
	
}

int main(void)
{
	
	//CONFIGURAÇÃO DAS GPIO'S
	
    DDRC = 0x00; //SETANDO TODAS AS PORTAS C COMO ENTRADAS
	DDRB = 0b11000000; //SETANDO AS PORTAS PB7 E PB6 COMO SAÍDAS PARA OS LEDS
	DDRD = 0xFF; //SETANDO TODAS AS PORTAS D COMO SAÍDAS (ENVIARÁ SINAL PARA O BUZZER)
	PORTC = 0x00; //DESATIVANDO TODOS OS RESISTORES PULL-UP DAS PORTAS C
	
	//CONFIGURAÇÃO DO ADC
	ADMUX = 0b00000000; //SETANDO O ADC PARA USAR O AREF COMO TENSÃO DE REFERÊNCIA, SETANDO O DESLOCAMENTO A DIREITA E SETANDO O ADC0 NA MULTIPLEXAÇÃO
	ADCSRA = 0b11101111; //LIGANDO O ADC, PERMITINDO CONVERSÃO, PERMITINDO AUTO TRIGGER, ATIVANDO DETECÇÃO DA INTERRUPÇÃO E SETANDO PRESCALER = 128
	ADCSRB = 0b00000011; //DETERMINANDO QUE O ADC FARÁ AS CONVERSÕES NA IGUALDADE DE COMPARAÇÃO A DO TC0
	DIDR0 = 0b00111110;	//DESABILITANDO OS OUTROS REGISTRADORES DE ADC
	
	//CONFIGURAÇÃO DO TIMER 0
	TCCR0A = 0b00000010; //CONFIGURANDO O TIMER EM MODO CTC
	TCCR0B = 0b00000011; //DEFININDO O PRESCALER PARA 64
	OCR0A = 249;		 //ARMAZENANDO O VALOR NO REGISTRADOR DE COMPARAÇÃO A
	TIMSK0 = 0x00;		 //DESABILITANDO TODAS AS MASCÁRAS DE INTERRUPÇÃO DO TIMER
	
	
	sei(); //HABILITANDO DAS INTERRUPÇÕES GLOBAIS
	
    while (1) 
    {
		
		if(leitura_adc >= 873) { // 873 É A PALAVRA DECIMAL APROXIMADA PARA UMA LEITURA NO DE TENSÃO EQUIVALENTE A 40°C NO ADC

			PORTB = 0b01000000; //ESCREVENDO NÍVEL ALTO NO LED VERDE QUANDO A TENSÃO FOR MENOR DO QUE APROXIMADAMENTE 4.268 V

		}


		else {

			_delay_ms(100);
			PORTB = 0b10000000; //ESCREVENDO NÍVEL ALTO NO LED VERMELHO
			PORTD = 0b00000100; //ESCREVENDO NÍVEL ALTO NO BUZZER
			
			_delay_ms(100);
			PORTB = 0b00000000; //ESCREVENDO NÍVEL BAIXO NO LED VERMELHO
			PORTD = 0b00000000; //ESCREVENDO NÍVEL BAIXO NO BUZZER

		} //RESUMINDO, O LED VERMELHO PISCA AO MESMO TEMPO QUE O BUZZER FICA APITANDO, INDICANDO ALERTE DE INCÊNDIO
    }
}

